--- 
version: '3.4'
services:
  db:
    build: 
      context: ./db

  stellar:
    build:
     context: ./stellar 
    image: chinkitp/stellar:latest
    volumes: 
    - "./data:/opt/stellar"
    environment:
      - POSTGRES_PASSWORD=mypass123
      - PGPASS=mypass123
      - NETWORK=pubnet
    depends_on:
      - "db"